name: Test app

on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
<<<<<<< HEAD
      uses: actions/checkout@v4
    - name: Setup java 17 as required by gradle
      uses: actions/setup-java@v4
=======
      uses: actions/checkout@v6
    - name: Setup java 17
      uses: actions/setup-java@v5
>>>>>>> upstream/master
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Execute tests
      run: |
        ./gradlew :app:testDebugUnitTest :terminal-emulator:test
